ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS client_id VARCHAR(100),
ADD COLUMN IF NOT EXISTS request_hash VARCHAR(128),
ADD COLUMN IF NOT EXISTS card_last4 VARCHAR(4),
ADD COLUMN IF NOT EXISTS card_fingerprint VARCHAR(128),
ADD COLUMN IF NOT EXISTS processing_started_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS processor_instance_id VARCHAR(100),
ADD COLUMN IF NOT EXISTS last_heartbeat_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS lease_expires_at TIMESTAMP;

ALTER TABLE outbox_events
ADD COLUMN IF NOT EXISTS attempts INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS claim_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS recovery_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS locked_by VARCHAR(100),
ADD COLUMN IF NOT EXISTS last_error TEXT;

CREATE TABLE IF NOT EXISTS dead_letter_jobs (
  id SERIAL PRIMARY KEY,
  job_id VARCHAR(100) UNIQUE NOT NULL,
  txn_id VARCHAR(50),
  queue_name VARCHAR(100) NOT NULL,
  payload JSONB NOT NULL,
  failed_reason TEXT NOT NULL,
  attempts_made INTEGER NOT NULL,
  failed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
