CREATE TABLE IF NOT EXISTS transactions (
  id SERIAL PRIMARY KEY,
  txn_id VARCHAR(50) UNIQUE NOT NULL,
  correlation_id VARCHAR(100) NOT NULL,
  idempotency_key VARCHAR(100) UNIQUE,
  request_hash VARCHAR(128),
  amount NUMERIC(12,2) NOT NULL,
  channel VARCHAR(50) NOT NULL,
  card_number VARCHAR(25),
  status VARCHAR(30) NOT NULL,
  received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  from_account VARCHAR(50),
  to_account VARCHAR(50),
  type VARCHAR(50),
  retry_count INTEGER DEFAULT 0,
  worker_id INTEGER,
  route VARCHAR(50),
  reason TEXT,
  result JSONB,
  processing_timeline JSONB
);

CREATE TABLE IF NOT EXISTS outbox_events (
  id SERIAL PRIMARY KEY,
  txn_id VARCHAR(50) UNIQUE NOT NULL,
  event_type VARCHAR(50) NOT NULL,
  payload JSONB NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  attempts INTEGER NOT NULL DEFAULT 0,
  last_error TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
